import { InventoryItems } from "@/features/inventory";

export type Item = {
  name: string;
  type: "song" | "item" | "mask" | "remain";
  image: string;
  quantity?: number;
};

export type Items = {
  ocarina: Item;
  heroBow: Item;
  heroBow2: Item;
  heroBow3: Item;
  fireArrow: Item;
  iceArrow: Item;
  lightArrow: Item;
  moonTear: Item;
  bomb: Item;
  bomb2: Item;
  bomb3: Item;
  keg: Item;
  magicBean: Item;
  roomKey: Item;
  letterToKafei: Item;
  landTitleDeed: Item;
  bottle1: Item;
  bottle2: Item;
  bottle3: Item;
  bottle4: Item;
  bottle5: Item;
  bottle6: Item;
  pictographBox: Item;
  lensOfTruth: Item;
  hookshot: Item;
  gfs: Item;
  swampTitleDeed: Item;
  goldDust: Item;
  dekuPrincess: Item;
  sword: Item;
  sword2: Item;
  sword3: Item;
  shield: Item;
  mirrorShield: Item;
  wallet: Item;
  wallet2: Item;
  magic: Item;
  mountainTitleDeed: Item;
  oceanTitleDeed: Item;
  letterToMama: Item;
  dekuNut: Item;
  dekuStick: Item;
  bombchu: Item;
  maskPostmanHat: Item;
  maskBlast: Item;
  maskAllNight: Item;
  maskStone: Item;
  maskGreatFairy: Item;
  maskDeku: Item;
  maskKeaton: Item;
  maskBremen: Item;
  maskBunnyHood: Item;
  maskDonGero: Item;
  maskScents: Item;
  maskGoron: Item;
  maskRomani: Item;
  maskCircusLeader: Item;
  maskKafei: Item;
  maskCouples: Item;
  maskTruth: Item;
  maskZora: Item;
  maskKamaro: Item;
  maskGibdo: Item;
  maskGaro: Item;
  maskCaptainHat: Item;
  maskGiant: Item;
  maskFierceDeity: Item;
  songTime: Item;
  songHealing: Item;
  songEpona: Item;
  songSoaring: Item;
  songStorms: Item;
  songSonata: Item;
  songLullaby: Item;
  songNewWave: Item;
  songElegy: Item;
  songOath: Item;
  remainsOdolwa: Item;
  remainsGoht: Item;
  remainsGyorg: Item;
  remainsTwinmold: Item;
};

export type SectionProps = {
  inventory: Partial<InventoryItems>;
};
